name: Deploy to EC2 on Push

on:
  push:
    branches:
      - test  # o 'test' si trabajas con la rama 'test'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 3.227.120.143
          username: ec2-user               # o ubuntu, depende de tu AMI
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            git clone https://github.com/Bryan03A/InterfaceWEB.git
            git pull origin main
            cd interface-service
            npm install
            pm2 delete interface-service || true
            pm2 start server.js --name interface-service
            pm2 save