name: Deploy to EC2 on Push

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 3.227.120.143
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Clonar o actualizar el repositorio
            if [ -d ~/InterfaceWEB ]; then
              cd ~/InterfaceWEB
              git pull origin test
            else
              git clone -b test https://github.com/Bryan03A/InterfaceWEB.git ~/InterfaceWEB
              cd ~/InterfaceWEB
            fi

            # Instalar dependencias del proyecto, incluyendo pm2 local
            npm install

            # Detener la app anterior si está corriendo
            npx pm2 delete interface-service || true

            # Iniciar la app con pm2 (vía npx)
            npx pm2 start server.js --name interface-service

            # Guardar configuración
            npx pm2 save